
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJkaXB0eWFAZ21haWwuY29tIiwiaWF0IjoxNjY3MTk2OTY2LCJleHAiOjE2NjcyMDQxNjZ9.wzqt4yZi-aFAX2DN31aLD4DNKqyf70mOfFLatwanR4Y
//Users
//register
POST  http://localhost:3001/user/create 
Content-Type: application/json

{
    "email" : "diptya@gmail.com",
    "password": "1234",
    "username": "bagus"
}

//login
###
POST  http://localhost:3001/user/login 
Content-Type: application/json

{
    "email": "diptya@gmail.com",
    "password": "1234"
}

//PHOTO
###
POST  http://localhost:3001/photos/create 
Content-Type: application/json
token: {{token}}

{
    "title" : "Foto joss",
    "caption": "Ini Foto",
    "image_url": "www.yt.com"
}

###
GET http://localhost:3001/photos
token: {{token}}

###
GET http://localhost:3001/getOne/23
token: {{token}}

###
PUT http://localhost:3001/update/23
Content-Type: application/json
token: {{token}}

{
    "title" : "Foto coba",
    "caption": "foto coba coba edit",
    "image_url": "www.fb.com"
}

###
DELETE http://localhost:3001/delete/23
token: {{token}}




//coba
###
GET http://localhost:3001/tulisan